### ISSUE TITLE
Decide Publisher

### ISSUE THREAD

**Issue by martingrundberg** [commonprofiles-care/fhir#10]
We need to decide on Publisher so we are consistent with the title of our collaboration

**Comment by RebeckaHansson** [comment]
Suggestions: 
Common FHIR profile vendor collaboration
Swedish FHIR profile vendor collaboration
Swedish FHIR Profiling Industry Collaboration

**Comment by RebeckaHansson** [comment]
Meeting decides on the following name:
Swedish FHIR vendor collaboration

As for now we are a Swedish collaboration, even if we expand to more countries in future we will probably need a sub grouping which can keep using this name.

**Comment by RebeckaHansson** [comment]
@martingrundberg can you close the issue?
