### ISSUE TITLE
Tags, what format

### ISSUE THREAD

**Issue by niclas86** [commonprofiles-care/fhir#101]
In what format should we go tags to create releases? @vadi2 do you have any suggestions for best practices

**Comment by vadi2** [comment]
We could go for semver as @MangalaEkanayake suggested and manually enter it when we need to make a new release. 

Best practices - what I've learnt over the years - is that you want to have validation of the tag to ensure the version passes a sanity check. Humans make mistakes :)

**Comment by niclas86** [comment]
@vadi2 You mean like a validation in the build process?

**Comment by vadi2** [comment]
That's right

**Comment by niclas86** [comment]
@vadi2 I think we could use this for it:
https://github.com/nowsprinting/check-version-format-action

**Comment by MangalaEkanayake** [comment]
> @vadi2 I think we could use this for it: https://github.com/nowsprinting/check-version-format-action

Sounds like a good way to integrate validation in to the pipeline.

**Comment by niclas86** [comment]
We can close this continue in #103
