### ISSUE TITLE
Include more patient data in the patient profile?

### ISSUE THREAD

**Issue by vjernelov** [commonprofiles-care/fhir#102]
The current lite version of the Patient profile is designed to support a use case where a more restricted set of patient data is passed between systems. We at Cambio have a bigger scope in mind due to the nature of our use case, so we'd be interested in seeing if others in the group also would be interested in expanding the scope of the current Patient profile.

If that's the case the suggestion is to establish a work group similar to the AuditEvent track we're having and start by looking at the HL7 Sweden base Patient profile to figure out if there are changes/restrictions/additions to that that we'd like to add for it to be useful from a Commonprofiles.care persepective.

So please raise your hand in this thread if you'd be interested in this!

**Comment by niclas86** [comment]
Please add uses cases @niclas86 @vjernelov

**Comment by vjernelov** [comment]
The adjustments made to the profile, removing the restrictions on the non-allowed elements is a great start from our PoV. Another case that came up internally is the need in a neo-natal use case to represent the actual hours the patient has lived. This can be done by including the https://build.fhir.org/ig/HL7/fhir-extensions/StructureDefinition-patient-birthTime.html as optional (since it's not really needed for adults), or optionally as a specific profile tailored to the neo-natal use case specifically.

**Comment by vadi2** [comment]
We'll move the neonatal / birthtime discussion to HL7 Sweden as this is not a usecase that all industry stakeholders have in this group.

**Comment by niclas86** [comment]
We keep this open and see what the outcome of the discussions in HL7 Sweden are first

**Comment by niclas86** [comment]
We wont include this given it´s very specific to neonatal use case, this is not common
