### ISSUE TITLE
Profiles to eHMs NGS service?

### ISSUE THREAD

**Issue by RebeckaHansson** [commonprofiles-care/fhir#11]

**Comment by mikael-nystrom-cambio** [comment]
https://www.ehalsomyndigheten.se/tjanster/yrkesverksam/nationella-gemensamma-specifikationer/

**Comment by peturv** [comment]
Decision 2022-04-01: Good idea. @mikael-nystrom-cambio will add a submission after @peturv publishes v1.0 during w14

**Comment by mikael-nystrom-cambio** [comment]
Hi @peturv , Have the profiles been published yet?

**Comment by niclas86** [comment]
Should be done on the 3/5, Rebecka and Niclas will notify in this issue

**Comment by niclas86** [comment]
We will look at this asp the service request is done

**Comment by niclas86** [comment]
@peturv will help to publish this

**Comment by vjernelov** [comment]
Since Cambio has done this already, we could also make sure the industry profiles are registered according to the process described by eHM.

**Comment by niclas86** [comment]
@RebeckaHansson will take this with @mikael-nystrom-cambio

**Comment by niclas86** [comment]
@mikael-nystrom-cambio is working on this and will take it asap

**Comment by mikael-nystrom-cambio** [comment]
The profiles are sent to eHMs NGS service for review. Next step is to wait until eHM contact us to go through their review results.

**Comment by mikael-nystrom-cambio** [comment]
Everything is completed from our side. We are waiting for eHM to publish the profiles and a news text about the profiles later today or in the beginning of next week.
