### ISSUE TITLE
Create info@commonprofiles.care

### ISSUE THREAD

**Issue by peturv** [commonprofiles-care/fhir#12]
Alias/forward for a group of users.
Individuals not permanently determined, will change over time.
@niclas86

**Comment by niclas86** [comment]
@niclas86 check how to send ity outside office365 tenant

**Comment by niclas86** [comment]
done

**Comment by RebeckaHansson** [comment]
Which persons will receive messages sent to this address?

**Comment by niclas86** [comment]
This is done
