### ISSUE TITLE
Upcoming profiling for booking flow

### ISSUE THREAD

**Issue by niclas86** [commonprofiles-care/fhir#13]
Please submit use cases in this issue so we have them for the profiling work going forward.
We will start this issues after service request is done.

**Comment by niclas86** [comment]
@niclas86 and joakim will submit use cases in this ticket 
@RebeckaHansson will submit cases

**Comment by RebeckaHansson** [comment]
Need from Cambio is to define FHIR profiles and pattern for reading appointments to e.g. present in an overview. 

Possible use cases:
* Get appointments based on criteria X (i.e. all appointments fulfilling this, regardless of which patient). 
* Get list of appointments for a particular patient

This would probably only need a slim Appointment model with the following information: 
- Appointment (start/end) date/time
- Patient
- Department/clinic
- Practitioners involved
- Slot
- Service to which you are booked
- Appointment type (video, face to face…)
- Some type of free text note

**Comment by niclas86** [comment]
Carasent needs/usecases

- Booking of patient digital and psychical based on criteria X
- Booking of medical equipment, rooms, etc.
- Arrival registration (this also becomes an encounter of some type)

Endpoint we can see:

- List time slots, booked and unbooked (filters)
- Make a booking of patient, equipment, room
- Cancel patient, equipment, room
- Change notifications

**Comment by niclas86** [comment]
I will book something week 35, @RebeckaHansson @vjernelov

**Comment by niclas86** [comment]
Niclas and Petur will create a draft and send out

**Comment by peturv** [comment]
@niclas86 we need to reserve time to work with this.

**Comment by niclas86** [comment]
I will show a preview at the 17/2

**Comment by vjernelov** [comment]
Niclas will ask for help from Petur and Vadim to get some details ironed out before presenting to the group.

**Comment by niclas86** [comment]
I have booked a meeting with Vadim to go trough this
