### ISSUE TITLE
Finalize ServiceRequest

### ISSUE THREAD

**Issue by RebeckaHansson** [commonprofiles-care/fhir#14]
To do:
Check correct way to reference Snomed CT value set for kontaktorsak. @mikael-nystrom-cambio  will check

**Comment by mikael-nystrom-cambio** [comment]
It would probably be the URI 

http://snomed.info/sct/45991000052106?fhir_vs=refset/60001000052100

that correctly reference the SNOMED CT refset for kontaktorsak.

Those interested can read more at https://confluence.ihtsdotools.org/display/DOCURI/2.1+URIs+for+Editions+and+Versions , http://build.fhir.org/snomedct.html#implicit and https://browser.ihtsdotools.org/?perspective=full&conceptId1=60001000052100&edition=MAIN/SNOMEDCT-SE/2021-11-30&release=&languages=sv,en .

**Comment by niclas86** [comment]
@peturv we have a version 1.0 that we will publish next week

**Comment by RebeckaHansson** [comment]
Hej @niclas86 och @peturv , vi på Cambio kommer snart äntligen igång med att implementera denna profil! :) Men tycks aldrig ha blivit publicerad i vår ImplementationGuide, vem är det som sitter på den senaste versionen?
