### ISSUE TITLE
Organization & Patient missing required cardinality on fields

### ISSUE THREAD

**Issue by peturv** [commonprofiles-care/fhir#22]
PatientSEVendorLite
- identifier:personnummer.value, identifier:samordningssnummer.value och identifier:nationelltReservnummer.value ska vara obligatoriskt
- telecom.system och telecom.value ska vara obligatoriskt

OrganizationSEVendorLite
- type:careProvider.coding.system, type:careProvider.coding.version and type:careProvider.coding.code ska vara obligatoriska
- type:careUnit.coding.system, type:careUnit.coding.version and type:careUnit.coding.code ska vara obligatoriska

**Comment by vjernelov** [comment]
@RebeckaHansson reviews before the issue closes.

**Comment by MangalaEkanayake** [comment]
Patient.identifier.value has not changed as expected. That needs to be in 1..1 in cardinality.

**Comment by peturv** [comment]
> Patient.identifier.value has not changed as expected. That needs to be in 1..1 in cardinality.

You are quite right. The 1.. seems to have disappeared during the harmonization with the HL7SE profiles. I have re-added and am putting you as reviewer.

**Comment by MangalaEkanayake** [comment]
> > Patient.identifier.value has not changed as expected. That needs to be in 1..1 in cardinality.
> 
> You are quite right. The 1.. seems to have disappeared during the harmonization with the HL7SE profiles. I have re-added and am putting you as reviewer.

Thanks for the quick response.
I have a minor concern: Don't we need to add must-support(MS) to identifier.value?

**Comment by niclas86** [comment]
Since we have 1..1 its stronger than must support @MangalaEkanayake
