### ISSUE TITLE
Talk to HL7 Sweden about creating PDL supporting profiles

### ISSUE THREAD

**Issue by vjernelov** [commonprofiles-care/fhir#28]
The need to create PDL supporting profiles is highly prioritized at Cambio for Q3-Q4 2022. This is something that would be best described on a national level, so we should suggest to HL7 Sweden that they should take lead on this.

The business concepts that need representation are:

- Blocks (inner and outer)
- Consents to shared electronic health records
- Access logs as defined by PDL

**Comment by RebeckaHansson** [comment]
Brought the need up in HL7 Sweden board and agreed it is something that the national base profile work group could work with. However this group does not have any activities currently since it is in need of a new fascilitator.

**Comment by niclas86** [comment]
Cambio @RebeckaHansson @vjernelov will show a suggestions for all, we will give feedback and try to have something to deliver together to HL7 in 4 weeks with every bodies consent

**Comment by niclas86** [comment]
https://simplifier.net/playground5/consentsjf

**Comment by RebeckaHansson** [comment]
Decided that those interested can have a look at the profiles and get back with feedback and questions until next meeting.

https://simplifier.net/playground5/consentblockse
https://simplifier.net/playground5/consentsjf

**Comment by niclas86** [comment]
@peturv please give feedback

**Comment by DanielVinberg** [comment]
Snomed koden: 416409005 "har nekat samtycke till att journal läggs in i lokalt delat elektroniskt journalregister" är lite tvetydig.
När jag läser texten tänker jag att man nekat att dela med någon annan än den enskilda vårdutföraren(läkaren). Men jag antar att man menar "har nekat samtycke till att journal läggs in i regionalt delat elektroniskt journalregister" och att det är ok att dela med övriga lokala enheten(avdelningen/vårdcentralen etc). 

Är man byråkrat så är bägge snomedkoder formulerade som att man inte ens får registrera denna data i antingen ett lokalt eller nationellt system. Patienten har nekat att data får läggas in alls i journalsystemet om det är ett regionalt system, snarare än att övriga delar av regionen inte har rätt att ta del av informationen i normalfallet.

Det kanske inte finns bättre val av koder dock?

"Inre spärr – innebär att du kan spärra på enhetsnivå, personal på övriga enheter inte har direktåtkomst till din journal."

"Yttre spärr - innebär din rätt att motsätta dig sammanhållen journal."

Hade en jurist hade gett tummen upp för formuleringarna :) ?

**Comment by niclas86** [comment]
We will send feedback to Socialstyrelsen in regards to @DanielVinberg sugestions above. @mikael-nystrom-cambio will help to send this.
We agree that we as a group should publish the profile the profiles, @RebeckaHansson will look to publish them

**Comment by RebeckaHansson** [comment]
Status:
This is ongoing, need to write as fsh files before publishing, not done yet.

**Comment by RebeckaHansson** [comment]
@vjernelov lyfter över fsh-fil för ConsentSJF (samtycke till sammanhållen journalföring) till github. 
@vjernelov  kollar om ConsentBlockSe finns i fsh-format redan, annars behövs en översättningsinsats. @peturv hjälper gärna till.

**Comment by vjernelov** [comment]
- ConsentSJF has been added to the Github.
- ConsentBlockSe doesn't exist in Cambio's repo, and the colleague who's been working with it has not been working this week.
  I will continue looking for it once they're back.

**Comment by vjernelov** [comment]
@vjernelov makes sure the fsh is correct before adding it to a new branch.

**Comment by vjernelov** [comment]
We have an internal review of the ConsentBlockSe booked for next week, to ensure it's complete, so I won't be creating a new branch with it until we've done that.
