### ISSUE TITLE
How to specify SCT concepts in codable concept

### ISSUE THREAD

**Issue by RebeckaHansson** [commonprofiles-care/fhir#29]
The following part of FHIR spec explains how to use FHIR with Snomed CT: https://hl7.org/fhir/snomedct.html

However it does not say exactly how to define a codable concept for the Swedish edition of SCT. The following suggestion is Cambios conclusion from the specification.

**Suggestion**

1. Specifying a coded value of a concept from the Swedish extension of Snomed CT:

       "system": "http://snomed.info/sct",

          "version": "http://snomed.info/sct/45991000052106/version/20220531"

          "code": "70831000052108"

2. Specifying a coded value of a concept from Snomed CT International:

       "system": "http://snomed.info/sct"

          "version": "http://snomed.info/sct/900000000000207008/version/20220831"

          "code": "75367002"

The date added should be the date of the latest release of the edition which is referred to at the time of defining this concept.

**Comment by niclas86** [comment]
@RebeckaHansson please ask about it in Zulip

**Comment by RebeckaHansson** [comment]
Zulip chat: https://chat.fhir.org/#narrow/stream/179166-implementers/topic/How.20to.20specify.20a.20SNOMED.20CT.20concept.20from.20a.20specific.20edition

**Comment by niclas86** [comment]
We are all for the suggestion

**Comment by niclas86** [comment]
@peturv and @niclas86 will update this on the Organisations profile
