### ISSUE TITLE
Decide on naming standard for SIP-profiles

### ISSUE THREAD

**Issue by peturv** [commonprofiles-care/fhir#3]
How should we name profiles? 
What should be included/excluded in the profile name?
Should we have default prefix/suffixes?

**Comment by danka74** [comment]
```<Parent resource/profile>SEIndustry<Profile type>?```

**Comment by markysand** [comment]
Base | Lite 👍

**Comment by markysand** [comment]
Owner/maintainer:

- Common | SoS | Cambio ...

**Comment by markysand** [comment]
Se | Eu | International ...

**Comment by martingrundberg** [comment]
Suggestion:
<Parent resource/profile><intended region><publisher><Profile type>

- Parent resoruce - This is **Patient**, **Organization**, **Observation**, **ServiceRequest** etc
- Intended region - This is for which region the profile is intended to be used, options are **SE** (Sweden), **Nord** (Nordics), **Eu** (Europe), **Int** (international)
- Publisher - This is who has published the profile, in our case this would be **Industry** as opposed to maybe **HL7 Sverige**
- Profile type: **Lite** - Intended purpose is a very small resource that contains only the most important resource information. Use cases are e.g. when resources are referenced and included in other resources, or when the resource is used for simpler scenarios like populating a combo box/drop down list. **Full** - Intended purpose is a full resource model that contains all information related to the main resource. Use cases are to see and update the full resource. 

Examples:

- OrganizationSEIndustryLite
- PatientSEIndustryLite
- PractitionerSEIndustryLite


Hopefully we can agree on this with our without adjustments next meeting

**Comment by martingrundberg** [comment]
Another example where we define a more specific resource from a more generic resource

ServiceRequestSelfReferralSEIndustryLite/Full

**Comment by martingrundberg** [comment]
Suggestion is to go with the above, but replace Industry with Vendor. 
Example:
OrganizationSeVendorLite

**Comment by martingrundberg** [comment]
Decision made during this meeting.

**Comment by martingrundberg** [comment]
Decision:
<Parent resource><Intended region><Publiser><Profile type>

**Parent resoruce** - This is Patient, Organization, Observation, ServiceRequest etc
**Intended region** - This is for which region the profile is intended to be used, options are **SE** (Sweden), **Nord** (Nordics), **Eu** (Europe), **Int** (international)
**Publisher** - This is who has published the profile, in our case this would be Industry as opposed to maybe HL7 Sverige. For the industry collaboration we will go with **Vendor**
**Profile type:**  **Lite** - Intended purpose is a very small resource that contains only the most important resource information. Use cases are e.g. when resources are referenced and included in other resources, or when the resource is used for simpler scenarios like populating a combo box/drop down list. **Full** - Intended purpose is a full resource model that contains all information related to the main resource. Use cases are to see and update the full resource.

The name will be in **UpperCamelCase**


OrganizationSEVendorLite
PatientSEVendorLite
PractitionerSEVendorLite

**Comment by peturv** [comment]
Added to readme.md
