### ISSUE TITLE
Create a website for commonprofile.care

### ISSUE THREAD

**Issue by niclas86** [commonprofiles-care/fhir#30]
Create a website for commonprofile.care
Niclas can put a wordpress that all members of the group can get access to and help to fill with content.
Rebecka, Pétur, Joakim, Niclas, Markus, Viktor

**Comment by peturv** [comment]
This is still in progress. A placeholder can be found at https://commonprofiles.azurewebsites.net/

**Comment by peturv** [comment]
The site is up at https://commonprofiles.care now. The profiles can be found at https://commonprofiles.care/fhir/index.html
