### ISSUE TITLE
Change to canonical url and package identifier.

### ISSUE THREAD

**Issue by peturv** [commonprofiles-care/fhir#37]
During work with preparing the IG for a proper publication through HL7:s tooling, I discovered that there is a requirement that either we register formally with HL7 (the process for this is unkown to me) resulting in changes to the HL7 FHIR publishing tool (publisher.jar) or that we include a "code" in our canonical url and package id.

The requirements for the code is that it shall be included as a separate part of the package id.
* commonprofiles.**[code]**.care
* commonprofiles.care.**[code]**
are both valid package id:s while commonprofiles.care[code] would be invalid.

The code shall also be added as a suffix to our url: https:/ /commonprofiles.care/**[code]**

My suggestion is that we adapt the code "fhir" so our new canonical url will be: https:/ /commonprofiles.care/fhir and our package id is either  `care.commonprofiles.fhir` or `commonprofiles.care.fhir`. I'd prefer the former myself.

Thoughts and/or objections? Lets take this up for discussion during next meeting.

**Comment by niclas86** [comment]
@RebeckaHansson @vjernelov please comment on this if it sound okay?

**Comment by niclas86** [comment]
@claudiaehr

**Comment by claudiaehr** [comment]
@peturv jag har kollat med Karolinskas FHIR-grupp och återkommer när jag har fått svar.

**Comment by vjernelov** [comment]
@peturv I'm not if it's a typo or if I misunderstand your opening post, but it seems you're contradicting yourself:

"commonprofiles.care.[code] is valid but commonprofiles.care.[code] is invalid"?

Regarding adding **fire** as the code, I have no objections and can't see how `care.commonprofiles.fhir` would be a problem.

**Comment by RebeckaHansson** [comment]
I also think using fhir as a code sounds ok.

**Comment by peturv** [comment]
> @peturv I'm not if it's a typo or if I misunderstand your opening post, but it seems you're contradicting yourself:
> 
> "commonprofiles.care.[code] is valid but commonprofiles.care.[code] is invalid"?
> 
> Regarding adding **fire** as the code, I have no objections and can't see how `care.commonprofiles.fhir` would be a problem.

Ah, yes. I apparently added a period as a reflex. Correcting the message

**Comment by claudiaehr** [comment]
@peturv I checked with Karolinskas FHIR-group before Christmas and there were no preferences so either care.commonprofiles.fhir or commonprofiles.care.fhir works for us.

**Comment by niclas86** [comment]
@peturv will update the profiles with care.commonprofiles.fhir
