### ISSUE TITLE
Allow multiple identifiers in PatientSEVendorLite

### ISSUE THREAD

**Issue by vjernelov** [commonprofiles-care/fhir#38]
We see a need to be able to support representing more than one patient identifier on a patient resource in our implementation. This is currently not possible using the PatientSEVendorLite profile.

Is there a specific reason why this is limited, and would the group object to changing that to element FROM 1..1 TO 1..*?

**Comment by niclas86** [comment]
@vjernelov will check this, it seems that the profiles supports this

**Comment by vjernelov** [comment]
Issue can be closed, the problem was on our end (out-of sync basically).
