### ISSUE TITLE
Restrict Patient.identifier.value to only allow digits for Personnummer slice?

### ISSUE THREAD

**Issue by vjernelov** [commonprofiles-care/fhir#39]
Currently the Patient.identifier.value (for Personnummer slice) allows for any kind of alphanumerical sign. Wouldn't it make sense to limit this to only be digits to make validation of erronous identifiers easier?

See https://github.com/HL7Sweden/basprofiler-r4/issues/51 for similar issue.

**Comment by vjernelov** [comment]
Cambio's suggested RegEx for personnummer is:

^(?:19|[2-9]\d)\d{2}(?:0[1-9]|1[012])(?:0[1-9]|[1-2]\d|3[0-1])\d{4}$

**Comment by niclas86** [comment]
The suggestions if that we use YYYYMMDDNNNN and apply a regex? Any one against?

**Comment by vjernelov** [comment]
`^(18|19|[2-9]\\d)\\d{2}(0[1-9]|1[012])([0-2]\\d|3[0-1])\\d{4}` 

also allows for edge cases where data about dead patients born in the 19th century are being used for research purposes. It's a more refined option than the one posted above.

**Comment by niclas86** [comment]
We are all for this suggestion, @vjernelov will create a branch with this suggestion.
