### ISSUE TITLE
Decide on base URL for our FHIR artifacts

### ISSUE THREAD

**Issue by RebeckaHansson** [commonprofiles-care/fhir#5]
Since we cannot use http://fhirsverige.se/ we need to decide on a new base URL in order to be able to publish our completed profiles and extensions.

**Comment by martingrundberg** [comment]
Here are a couple of suggestions to get people thinking. I think perhaps we should keep it in English like other things, feels better. I think it can also be a good idea to not explicitly state that these are Swedish profiles. We can still focus on the Swedish requirements, but not have a domain that limits collaboration with vendors in e.g. other Nordic countries in the future. 

- profiles.healthcare
- profiles.care
- industryprofiles.care
- industryprofiles.healthcare
- collaboration.healthcare
- industrycollaboration.healthcare
- industrycollaboration.care
- commonprofiles.care
- commonprofiles.healthcare
- ecosystem.healthcare
- ecosystemprofiles.care
- ecosystemprofiles.healthcare
- datafirst.care
- datafirst.healthcare
- sharingiscaring.care
- sharingiscaring.healthcare

If we want to stick with Swedish domains, here are some suggestions:

- ecosystemprofiles.se
- industryprofiles.se
- collaboration.se
- industrycollaboration.se
- commonprofiles.se
- datafirst.se

If we want to go with full Swedish domain names, here are some suggestions:

- ekosystemprofiler.se
- industriprofiler.se
- gemensammaprofiler.se


Overall, I like the idea of the ecosystem where multiple actors collaborate. So I like the ecosystem domains, but other ideas are welcome!

**Comment by mikael-nystrom-cambio** [comment]
I like the names with common profiles. I also think that it would be appropriate to point out that the profiles are created in Sweden, so I like the Swedish domain names. My view is that wouldn't decrease the possibilities to also use them in other Nordic countries.

**Comment by niclas86** [comment]
I like short easy to remember domain like profiles.care
I like it not to be Swedish (Sorry Mike :)) rather have it like profiles.care/se or profiles.care/no :)

**Comment by martingrundberg** [comment]
Decision on meeting today that we should go with **commonprofiles.care**.

**Comment by niclas86** [comment]
The domain has been purchased, publishing follows in #8

**Comment by RebeckaHansson** [comment]
Reopening just to clarify what the resulting canonical URL:s for our FHIR artifacts will look now that we have set the domain. 

Suggestion:
https:// commonprofiles.care/< resource type >/<profile/extension/value set name>/< version >

Examples:
https://commonprofiles.care/StructureDefinition/OrganizationSEVendorLite/v1
https://commonprofiles.care/ValueSet/PerfectNameOfAPerfectValueSet/v1
https://commonprofiles.care/StructureDefinition/common-hsaHierarchy/v1

Including the resource type follows the same pattern which is used both for the Swedish base profiles and also for the FHIR base resources and profiles. Examples:
http://build.fhir.org/ig/HL7Sweden/basprofiler-r4/StructureDefinition-SEBaseOrganization.html
https://www.hl7.org/fhir/bodyweight.html

**Comment by peturv** [comment]
Decision to go with suggestion above 2022-04-01.
Added to readme.md
