### ISSUE TITLE
Restructuring of Patient identifier invariants

### ISSUE THREAD

**Issue by vjernelov** [commonprofiles-care/fhir#50]
The current solution is based on a new profile derived from the PatientSEVendorLite one.

We should instead seperate the invariants into a seperate file and include the "obeys" lines from the PatientIdentifierPatternConformanceSE files in the PatientSEVEndorLite.

The reason for this is that we don't want people to use PatientIdentifierPatternConformanceSE as their actual Patient profile, but instead keep using the PatientSEVendorLite one.

A PR is already in place where this fix is done:
https://github.com/SvenskaIndustriProfiler/fhir/pull/49

**Comment by niclas86** [comment]
We thinks this is a good solutions and approves the PR
