### ISSUE TITLE
Changes to how fields are included/excluded

### ISSUE THREAD

**Issue by peturv** [commonprofiles-care/fhir#59]
Currently we are using MS and minimum cardinality of 1 to define inclusion, and maximum cardinality of 0 to enforce exclusion of fields from our profiles. This is problematic while also going against best practices.

By setting a maximum cardinality to 0 in order to exclude information there are a couple of issues being caused:
* Custom implementation are needed in order to use the profile. Information that could otherwise have been safely ignored by the receiver MUST now be removed by the sender.
* Profiles become non-extensible. If another party has a need to follow the profile while reintroducing one of the fields the only way to solve that is by creating custom extensions which is detrimental to interoperability.

We are seeing issues with this already within our group

Instead we should utilize the must support with a proper definition to declare which fields are included, and simply leave fields that are not included untouched.

This has been addressed from other parties as well: https://build.fhir.org/ig/FHIR/ig-guidance/best-practice.html

**Comment by vjernelov** [comment]
The group agreed this changes makes a lot of sense from different perspectives. No voice was raised to keep things as they are today. Therefor, the next step is to:

1. Create sub-issues for all profiles affected by this change
2. Create a sub-issue for detailing the use of Must Support in the ImplementationGuide

**Comment by niclas86** [comment]
@vadi2 could you help to write our definition of MS and post it here so we could public that with updated profiles

**Comment by niclas86** [comment]
@vadi2 please have a look at above

**Comment by niclas86** [comment]
@vadi2 please again could you help with this?

**Comment by vadi2** [comment]
See https://github.com/commonprofiles-care/fhir/issues/85#issuecomment-1824625583
