### ISSUE TITLE
Practitioner profile

### ISSUE THREAD

**Issue by martingrundberg** [commonprofiles-care/fhir#6]
We agreed 2022-02-18 that we will be creating a profile for Practitioner as the next industry profile after the finalization of the Organization

Niclas, Petur, Päivi, Daniel, Markus S...

**Comment by martingrundberg** [comment]
Martin books

**Comment by martingrundberg** [comment]
Doodle sent https://doodle.com/poll/3exu6xmr86ki6xux?utm_source=poll&utm_medium=link

**Comment by martingrundberg** [comment]
Profile can be found here, will be sent to Niclas and Petur next week after a last review. 
https://simplifier.net/Playground5/PractitionerSEIndustryLite/~overview

**Comment by peturv** [comment]
Decision to go with proposed profile 2022-04-01
Will be published by Pétur week 14
