### ISSUE TITLE
Update the contributing.md with details around changes and releases

### ISSUE THREAD

**Issue by vjernelov** [commonprofiles-care/fhir#60]
We need to document our ways of working with respect to how we merge Pull Requests and request new releases. This information should be put in the contributing.md file.

The base idea is that anyone can create a PR, but that PR then needs to be accepted by at least one person from another organization actively participating in the collaboration. One important aspect here is that SMALL changes must be quickly reviewed (2-3 **business** days). 
A basic requirement is that AT LEAST one other person from ANOTHER organization must approve the change. That means that even if we all fail our commitment and nobody responds, the PR CANNOT be merged.

Larger or more complex changes or additions shall be discussed in a regular group meeting before being merged.

As soon as someone wants a new release an **issue** should be created.

**Comment by niclas86** [comment]
@niclas86 I could write a markup for this in this issue as a suggestion to be commented

**Comment by niclas86** [comment]
I will writes this next week and put in a comment here

**Comment by niclas86** [comment]
Changes:
All changes should have an issue in Github that well describes why and what the change aims to achieve. All changes should be made in feature branches and shall be code reviewed by at least 2 different companies in the group

Release:
To make a new release, a pull request should be approved by at least 2 different companies in the group. The release should be taged in git with a release number. This release number correlate with the version publicized in the IG.

**Comment by niclas86** [comment]
Tag @claudiaehr when this branch exists and she will look at this change

**Comment by niclas86** [comment]
@vadi2 @vjernelov @claudiaehr will review the PR
