### ISSUE TITLE
Fix QA errors/warnings

### ISSUE THREAD

**Issue by vadi2** [commonprofiles-care/fhir#61]
Our IG has quite a few errors and warnings: https://build.fhir.org/ig/SvenskaIndustriProfiler/fhir/qa.min.html and they are valid issues that require addressing. Once they are fixed, applying good discipline to never introduce new errors or warnings - in my experience - makes it much easier to stay on top of them.

I have filed a similar issue on [HL7 Sweden repo](https://github.com/HL7Sweden/basprofiler-r4/issues/56).

**Comment by niclas86** [comment]
Start with cleaning the once we created our self, however some needs to be addressed by HL7 Sweden. This should be reported to them

**Comment by niclas86** [comment]
@peturv has been in contact with HL7 so they can act on the issues

**Comment by niclas86** [comment]
@peturv will create PR soon on this

**Comment by niclas86** [comment]
This is merge to master and need a release
