### ISSUE TITLE
Request for new package release

### ISSUE THREAD

**Issue by vjernelov** [commonprofiles-care/fhir#62]
Cambio are interested in getting access to the bug fix addressed in https://github.com/SvenskaIndustriProfiler/fhir/pull/58

Our understanding is that this should be considered a PATCH level change according to SemVer's definitions:

> Given a version number MAJOR.MINOR.PATCH, increment the:
>
>MAJOR version when you make incompatible API changes
>MINOR version when you add functionality in a backward compatible manner
>PATCH version when you make backward compatible bug fixes

**Comment by vadi2** [comment]
Good with me, keeping in mind future changes will be done according to https://github.com/SvenskaIndustriProfiler/fhir/issues/60

**Comment by vjernelov** [comment]
Any update on this? I was under the impression from the meeting we had 3 weeks ago that the actual release process was going to be a quick one once a request was made.

**Comment by vadi2** [comment]
Not sure how to do them myself - @peturv?

**Comment by niclas86** [comment]
This has been fixed and merged, @peturv will create a release

**Comment by peturv** [comment]
@vjernelov I've been looking at this on friday and during the weekend. Publisher behavior has been changed and am now getting exceptions during the publication process. Am still debugging if the error is in publisher code or our setup. Hopefully done soon.

**Comment by peturv** [comment]
I've published v1.0.1 to the website. There is still an issue publishing new versions, but it is manageable through a workaround. @vjernelov please validate that expected changes are in place and if everything looks good, close the issue.

**Comment by vjernelov** [comment]
@MangalaEkanayake , could you please verify?

**Comment by MangalaEkanayake** [comment]
> @MangalaEkanayake , could you please verify?

Verified! I can see https://commonprofiles.care/fhir/1.0.1/index.html with the latest changes.
