### ISSUE TITLE
Define official name for our group

### ISSUE THREAD

**Issue by claudiaehr** [commonprofiles-care/fhir#63]
According to @niclas86 we don't have an official name for our group. In the NGS tjänsten (https://www.ehalsomyndigheten.se/yrkesverksam/ngs-tjansten/), "Svenska leverantörssamarbetet för HL7 FHIR" is used. Even industriprofilgruppen seems to be used (at least at Karolinska). Are there other names in use?

The objective of this issue is to define an official name for our group.

**Comment by peturv** [comment]
Add one suggestion / comment below:
(We need a name in both English and Swedish)

**Comment by peturv** [comment]
Svenskt FHIR-samarbete

**Comment by peturv** [comment]
Swedish common FHIR ptofile collaboration

**Comment by peturv** [comment]
Samarbetsgrupp för svenska FHIR-profiler

**Comment by peturv** [comment]
Svenska FHIR-gruppen = SFG

**Comment by niclas86** [comment]
We have decided on "Svenska FHIR-gruppen = SFG"/"Swedish FHIR Collaboration"

**Comment by niclas86** [comment]
@mikael-nystrom-cambio could you update as suggestions above

**Comment by mikael-nystrom-cambio** [comment]
Jag har idag skickat följande brev till E-hälsomyndighetens administratör av NGS-tjänsten.

Hej!

Jag har tidigare rapporterad in tre FHIR-profiler i NGS-tjänsten från vårt leverantörssamarbete; [OrganizationSEVendorLite | Nationella gemensamma specifikationer (ehalsomyndigheten.se)](https://ngs.ehalsomyndigheten.se/specifikation/svlevsamarb/org), [PatientSEVendorLite | Nationella gemensamma specifikationer (ehalsomyndigheten.se)](https://ngs.ehalsomyndigheten.se/specifikation/svlevsamarb/pat) och [PractitionerSEVendorLite | Nationella gemensamma specifikationer (ehalsomyndigheten.se)](https://ngs.ehalsomyndigheten.se/specifikation/svlevsamarb/hslpersonal). Jag rapporterade in profilerna under vårt leverantörssamarbetes tillfälliga namn ”Svenska leverantörssamarbetet för HL7 FHIR”. Nu har det dock beslutats att namnet i stället ska vara ”Svenska FHIR-gruppen” och jag skulle därför vilja få vårt namn uppdaterat till det nya i NGS-tjänsten.

	Med vänliga hälsningar
	Mikael Nyström

**Comment by mikael-nystrom-cambio** [comment]
Svar från E-hälsomyndigheten:

Hej

Namnet är nu uppdaterat i NGS-tjänsten.

Med vänliga hälsningar
Vivéca Busck Håkans, Helena Nilsson, Anne Simmasgård
Nationella gemensamma e-hälsospecifikationer
E-hälsomyndigheten
