### ISSUE TITLE
Enable more people to perform publication

### ISSUE THREAD

**Issue by peturv** [commonprofiles-care/fhir#64]
Having just one person that handles publication of guides is not optimal, so it would be good to share both permissions and knowledge.

Suggested persons are @MangalaEkanayake and @vadi2 
I ( @peturv ) will call for a meeting to discuss process and distribute credentlais. If there are any pothers that should be included, let please add as a comment.

**Comment by peturv** [comment]
Related to #60

**Comment by claudiaehr** [comment]
@peturv, jag är också gärna med på en sådan genomgång
