### ISSUE TITLE
Do we need to maintain publish folder in master?

### ISSUE THREAD

**Issue by MangalaEkanayake** [commonprofiles-care/fhir#65]
I can see published artifacts in the folder https://github.com/SvenskaIndustriProfiler/fhir/tree/master/publish
May be we need to ignore the publish folder in git ignore file?

**Comment by peturv** [comment]
Some of the files in the publish folder are needed.
But I'll do a repository split and put the publication files in a separate gitmodule/repository so it doesn't need to be downloaded for normal usage. Created a branch for this and will implement.

**Comment by niclas86** [comment]
@MangalaEkanayake please have a look at the pull request on the branch connected to this issue
