### ISSUE TITLE
Rename github project

### ISSUE THREAD

**Issue by peturv** [commonprofiles-care/fhir#69]
Since we are moving to a more generic, less excluding name for the group, we should rename the github project name as well.
This will effect the following:
* URL to github from commonprofiles web site
* git remote definitions where the repository has been checked out (local computers).
* Bookmarks

**Comment by peturv** [comment]
Suggestion for new group name is: "commonprofiles"

**Comment by niclas86** [comment]
We change to "commonprofiles-care"

**Comment by peturv** [comment]
This has now been performed. Update your local git remotes using:
`git remote set-url origin git@github.com:commonprofiles-care/fhir.git`

Readme and hooks need to be updated as well
