### ISSUE TITLE
Naming standard for extensions

### ISSUE THREAD

**Issue by RebeckaHansson** [commonprofiles-care/fhir#7]
Decision on naming standard for extensions.
Good if we can visualize in which context the extension should be used, maybe it is more common and can be used on a lot of different resources or maybe it is more specific to a certain resource or use case. 

Suggestion: 
* Use the following format: [context]-[name].
* For each part [context]or[name], use lowerCamelCase
* If the extension is useable in multiple contexts, use "common" instead of the context, common-[name], e.g. common-age.
* If extension is only usable in one context, e.g. Practitioner, use the context Practitioner-[name]

Example:
common-hsaHierarchy

**Comment by martingrundberg** [comment]
Decision during meeting today to go with the above suggestion
