### ISSUE TITLE
Review consent profile

### ISSUE THREAD

**Issue by peturv** [commonprofiles-care/fhir#72]
New versions of FSH throw errors during build:
` Consent.provision.actor[grantor]: An element with a slice name should not define its own slicing. Instead, append additional discriminators to the original slicing on the base element. `
Seems to be caused by the additional slicing performed on provision.actor to achieve:
`* provision.actor[grantor][personnummer].reference.identifier 1..`

Since this is currently blocking new builds while you, at the same time are already in the process of reviewing the profile , I'm moving the profile to a separate branch and removing it from master until the issues are solved.

**Comment by niclas86** [comment]
We close this and it will be following in the #75
