### ISSUE TITLE
Publisher guide

### ISSUE THREAD

**Issue by niclas86** [commonprofiles-care/fhir#78]
Create a publish.md file that describe the process on how to make a release :)

**Comment by peturv** [comment]
Notes to self:
1. Define prerequisites
2. Simple step-by-step guide
( 3. Set up github actions to auto build publication artifacts on tagging. )

**Comment by niclas86** [comment]
@niclas86 make sure to put this in a releade.md file

**Comment by niclas86** [comment]
@vadi2 @MangalaEkanayake @peturv suggestions on format for the tags?

**Comment by vadi2** [comment]
I don't have a strong preference for this - something like YYYY.# would work where it's not too hard on the tooling or people to deal with.

YYYY would be the year, # would be an incremented integer that starts with 1 - so we'd have `2024.1`, `2024.2` and so on.

**Comment by MangalaEkanayake** [comment]
> @vadi2 @MangalaEkanayake @peturv suggestions on format for the tags?

How about use the Semantic Versioning for releases? https://semver.org/

**Comment by vadi2** [comment]
That would work just as well.
