### ISSUE TITLE
Create a web site for commonprofiles.care

### ISSUE THREAD

**Issue by niclas86** [commonprofiles-care/fhir#8]
Public a website on commonprofiles.care where info can be posted together with profiles

**Comment by niclas86** [comment]
DNS has been setup, need to decided where and what to host

**Comment by peturv** [comment]
For now we redirect site to build.fhir.org from when profile v1.0 is built.

**Comment by peturv** [comment]
http://build.fhir.org/ig/SvenskaIndustriProfiler/fhir/branches/master/

**Comment by niclas86** [comment]
This is now setup correct
