### ISSUE TITLE
Link does not resolve

### ISSUE THREAD

**Issue by claudiaehr** [commonprofiles-care/fhir#82]
The link on https://commonprofiles.care/fhir/history.html leading to the current version does not resolve (see symbol highlighted in yellow below) 
![image](https://github.com/commonprofiles-care/fhir/assets/77503664/f7424dc3-4172-4027-b957-c2f220245fc8)

![image](https://github.com/commonprofiles-care/fhir/assets/77503664/a85540d0-9c8e-49ef-b199-d76aee5b4505)

Should that be fixed?

**Comment by peturv** [comment]
Yes, this will be fixed "automatically" during next release. It's a problem related to our name-change.

**Comment by peturv** [comment]
I fixed this manually for now. The fix should be kept intact in future releases.
