### ISSUE TITLE
Profile names with "Vendor" in them

### ISSUE THREAD

**Issue by abebehailu** [commonprofiles-care/fhir#84]
I can see that some of the profiles in this repo has the name "Vendor" in them e.g. https://github.com/commonprofiles-care/fhir/blob/master/input/fsh/PatientSEVendorLite.fsh. I understand that it is a legacy. I think we should give profiles names without the vendor in them since this group now has representatives from hospitals as well.

**Comment by peturv** [comment]
Examples of replacements:
SECommons
SEC
SECPC

**Comment by niclas86** [comment]
We should change the readme.md with the suggestion SECommons

**Comment by MangalaEkanayake** [comment]
PR is ready: https://github.com/commonprofiles-care/fhir/pull/88
