### ISSUE TITLE
Our definition of must support

### ISSUE THREAD

**Issue by niclas86** [commonprofiles-care/fhir#85]
Suggestion, please comment:

Producer:
If you have the data, you must submit data
Consumer:
If you can retrieve data, your must save data

The definition should be put in the IG and readme.md

**Comment by vadi2** [comment]
How about this -

> [Must Support](http://hl7.org/fhir/R4/profiling.html#mustsupport) in this implementation guide is used to indicate that a particular element is mapped a measure set variable, and must be populated with data should it be available in the system.

> In case an element cannot be populated because it is not available in the source system, if the cardinality rules allow it, the element can be left unfilled. In case the cardinality rules require an element to be populated, the [Data Absent Reason](http://hl7.org/fhir/R4/extension-data-absent-reason.html) extension SHALL be used.

TBD add text for consumer.

**Comment by vadi2** [comment]
How about this version?

> [Must Support](http://hl7.org/fhir/R4/profiling.html#mustsupport) in this implementation guide is used to indicate that if particular element is available in the source system, it SHALL be populated with data. The system consuming the data SHALL be able to save the data and act on it accordingly.
>
> In case an element cannot be populated because it is not available in the source system, if the cardinality rules allow it, the element can be left unfilled. In case the cardinality rules require an element to be populated, the [Data Absent Reason](http://hl7.org/fhir/R4/extension-data-absent-reason.html) extension SHALL be used.

**Comment by niclas86** [comment]
Update the readme.md file wityh this definition

**Comment by niclas86** [comment]
@niclas86 do the change in the branch connected to this issue
