### ISSUE TITLE
Review and consolidate Patient, Organization and Practitioner

### ISSUE THREAD

**Issue by martingrundberg** [commonprofiles-care/fhir#9]
Martin and Rebecka reviews them and ensures they are consistent and have correct naming, then sends them to Niclas and Petur

**Comment by RebeckaHansson** [comment]
Review done and consistency edits done, profiles are updated in Cambios Simplifier "playground" project and sent to Niclas and Petur.
https://simplifier.net/playground5/practitionerseindustrylite
https://simplifier.net/playground5/patientsevendorlite
https://simplifier.net/playground5/organizationsebaseindustry
https://simplifier.net/playground5/commonhsahierarchy

Some questions that came up during the review:

- Swedish base profile group seems to have created new URIs for personnummer, samordningsnummer and reservnummer. We could not find if these URIs are used elsewhere. Do we still want to inherit this to our profile for patient?
- Swedish base profile defines and OID for national temporary id, should we also define a solution for local temporary id:s?
- How should you interpret the extensions put on HumanName (used in Patient and Practitioner)? e.g. middleName, ownFamily. Can we produce examples?

**Comment by RebeckaHansson** [comment]
Decisions from meeting:

_- Swedish base profile group seems to have created new URIs for personnummer, samordningsnummer and reservnummer. We could not find if these URIs are used elsewhere. Do we still want to inherit this to our profile for patient?_

- We will keep these URIs in our profile but need to describe how to manage this in our ImplementationGuide. Will create a new issue for this. We should also contact Inera (nat. reservnr) and Skatteverket (personnr, samordningsnr) to ask to formally declare these as a name space for person identifiers. For now we will use the URL:s we inherited from base profile. 

_- Swedish base profile defines and OID for national temporary id, should we also define a solution for local temporary id:s?_
- No, the profile should be defined on a national level. If regional requirements exists that should be handled separately.

_How should you interpret the extensions put on HumanName (used in Patient and Practitioner)? e.g. middleName, ownFamily. Can we produce examples?_
- No change in profile. Good if we can produce examples.

**Comment by RebeckaHansson** [comment]
Goal for next time: Profiles published and we will give a formal yes for version 1 of them.

**Comment by peturv** [comment]
Plan to publish w14

**Comment by niclas86** [comment]
Rebecka and Niclas will try to public Practitioner on 3/5
Patient and Organization is publish

**Comment by niclas86** [comment]
@peturv please fix the naming of patient profile

**Comment by niclas86** [comment]
@peturv please fix the naming of patient profile
