### ISSUE TITLE
Change name to Swedish FHIR group

### ISSUE THREAD

**Issue by claudiaehr** [commonprofiles-care/fhir#90]
The heading Swedish FHIR profile på https://[commonprofiles.care](https://commonprofiles.care/)/ should maybe be changed to Swedish FHIR group?

**Comment by niclas86** [comment]
Done

**Comment by claudiaehr** [comment]
The old name is still used on https://commonprofiles.care/fhir/index.html, see 
![image](https://github.com/commonprofiles-care/fhir/assets/77503664/ab486a6d-6ddf-4894-b1b4-d066d223c7be)

**Comment by niclas86** [comment]
@niclas86 make the change in the publication-request.json file
