### ISSUE TITLE
Support ehrid in common patient profile?

### ISSUE THREAD

**Issue by claudiaehr** [commonprofiles-care/fhir#92]
Karolinska has identified the need to manage ehrid as part of the patient profile. What is the Swedish FHIR group's position on updating the common patient profile to support ehrid?

**Comment by vadi2** [comment]
I wonder how would that be different from the personnummer/samordningsnummer?

**Comment by vjernelov** [comment]
The way openEHR talks about the ids make them different than personnummer or samordningsnummer. For instance, there isn't simply one system you use to say "this is an ehr id". We spent significant time wrestling with this problem together with KS and concluded the following:

<html xmlns:m="http://schemas.microsoft.com/office/2004/12/omml"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=PowerPoint.Slide>
<meta name=Generator content="Microsoft PowerPoint 15">
<style>

</style>
</head>

<body>



Parameter | Description
-- | --
openehr-ehr-id | The unique identifier for the EHR   within the CDR instance.
openehr-system-id | The unique identifier of the CDR instance.
care-provider-id | A unique ID of the care provider   assigning the EHR id, e.g. the national organizational   number of the care provider.
care-provider-id-system | The system of the id used to identify   the care provider, e.g. the national organizational   number.
care-provider-name | The name of the care provider assigning   the EHR id.
cdr-purpose | The business purpose   the CDR caters   to




</body>

</html>

![image](https://github.com/commonprofiles-care/fhir/assets/33927741/6f9d2884-b310-4db7-8301-b6ed619d46ae)

**Comment by vadi2** [comment]
The more identifiers we can exchange, the better :)

I'm not against the idea. Is `urn:openehr` valid? openehr isn't in the list of namespaces: https://www.iana.org/assignments/urn-namespaces/urn-namespaces.xhtml, but I also don't know if you can use custom ones just like that.

Also, have you checked with the openehr community if anyone has already mapped these identifiers?

**Comment by claudiaehr** [comment]
Discussed issue in meeting. Niclas is also positive about taking a closer look at the issue. We decided on starting work when work on AuditEvent is finished/has gotten further https://github.com/commonprofiles-care/fhir/issues/89

**Comment by niclas86** [comment]
Could be something to bring to HL7 Sweden, but we would need to discuss this in the group first

**Comment by niclas86** [comment]
@danka74 you think this could be brought to the HL7 Sweden group? Can you bring it?

**Comment by vjernelov** [comment]
We as a group need to decide how to approach this. I'll create a new issue suggesting how to approach it.

**Comment by niclas86** [comment]
We have task force in HL7 Sweden that will discuss this onward

**Comment by vadi2** [comment]
@vjernelov is chairing the HL7 Sweden patient group, will raise it at the 2024-04-15 meeting and create an issue in hl7 se repository.

**Comment by vjernelov** [comment]
Issue raised in https://github.com/HL7Sweden/basprofiler-r4/issues/72 so I will close this issue.
