### ISSUE TITLE
Additional examples for the Commonprofiles.care profiles

### ISSUE THREAD

**Issue by vjernelov** [commonprofiles-care/fhir#94]
We've received requests internally from our devs and QAs about additional examples that show how different use cases are supported by the profiles provided by Commonprofiles.care. Specifically questions about how the use of extensions pan out in actual resources and so on. 

If we think more actors would be interested in this I suggest we could make a small effort and create some more/better/richer example resources.

**Comment by vadi2** [comment]
Definitely needed. As a side note, chatgpt is helpful with getting most of an example in place - you just need to do some polishing.

**Comment by niclas86** [comment]
@vadi2 will look into this
